import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useState } from 'react'
import baseURL from '@/api'
import { GetStaticProps } from 'next'

export default function Home() {
  const [data, setData] = useState()
  return (
    <>
      <Head>
        <title>Demo Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        this is home page
        <div>
          <Link href='/blogs/[slug]' as='/blogs/1'>
            First blog
            </Link>
          <Link href='/blogs/[slug]' as='/blogs/2'>
            Second blog
            </Link>
          <Link href='/blogs/[slug]' as='/blogs/3'>
            Third blog
            </Link>
        </div>
      </main>
    </>
  )
}
// export const getStaticProps:GetStaticProps=async(context)=>{
//   const data=await fetch(`${baseURL}/products`)
//   // console.log(data)
//   return {
//     props:{
      
//     }
//   }
// }
